Feat/docker
HIP-infrastructure/frontend pull request #36
Opened 2024-06-03 12:13 UTC by sami-sweng

2024-07-31 07:09 UTC, greut commented
@sami-sweng what is this good for? Also, please don't target "master" first.

2024-07-31 07:11 UTC, greut requested changes
The "HIP" is currently running on CSCS/Exoscale with our GitLab registry. I don't see how those changes are playing well with that setup. Please clarify.

2024-08-06 08:02 UTC, sami-sweng commented
https://github.com/CHORUS-TRE/v1-dockerized/blob/master/build/stage2-files/install.sh#L23

2024-08-06 08:30 UTC, greut commented
> https://github.com/CHORUS-TRE/v1-dockerized/blob/master/build/stage2-files/install.sh#L23

ack, then that PR won't be merged, ever. Is that correct?

2025-04-04 07:09 UTC, johaab commented
@sami-sweng @floriansipp Can I close this PR or are you expecting it to be merged at some point?

2026-07-01 13:58 UTC, closed without merging